apiVersion: v1
kind: Service
metadata:
  name: webdemo
  labels:
    app: webdemo
spec:
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
  selector:
    app: webdemo
    tier: frontend
  type: ClusterIP
root@demo-kube-master:/home/msdemo/webdemo# cat webdemo-deployment.yml 
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: webdemo
  labels:
    app: webdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webdemo
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webdemo
        tier: frontend
    spec:
      containers:
      - image: dockerprivateregistry.demos.ms-biznetgio.net/webdemo
        name: webapp
        ports:
        - containerPort: 80
        - containerPort: 443
      imagePullSecrets:
      - name: regcred
