apiVersion: apps/v1 
kind: Deployment
metadata:
  name: webdemo
  labels:
    app: webdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webdemo
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webdemo
        tier: frontend
    spec:
      containers:
      - image: dockerprivateregistry.demos.ms-biznetgio.net/webdemo
        name: webapp
        ports:
        - containerPort: 80
        - containerPort: 443
      imagePullSecrets:
      - name: regcred
