apiVersion: v1
kind: Service
metadata:
  name: webdemo
  labels:
    app: webdemo
spec:
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
  selector:
    app: webdemo
    tier: frontend
  type: ClusterIP
