apiVersion: apps/v1 
kind: Deployment
metadata:
  name: webdemo
  labels:
    app: webdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webdemo
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webdemo
        tier: frontend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: webdemo  
        image: dockerprivateregistry.demos.ms-biznetgio.net/webdemo
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
           memory: 200M
           cpu: 200m
          limits:
           memory: 300M
           cpu: 300m
